Best_practice in toc eingefügt
Methods-Berlin/RLernplattform pull request #222
Opened 2023-07-29 13:13 UTC by behnkec

Ich habe mal einen Aufschlag für die Best Practice Seite gemacht. Macht gerne noch Vorschläge, ich war mir nicht sicher, was alles da rein soll.

2023-07-29 14:32 UTC, jhorzek commented
Ich habe mir die Dateien gerade angeschaut und ich glaube, Du hast versehentlich ein paar temporäre Dateien mit commited, die erstellt werden, wenn man die Seite lokal rendert (z.B. der bootstrap order). Versuche mal folgendes lokal bei dir:

```
git checkout main
git pull origin main
git branch best_practice_cleaned
git checkout behnkec-best-practice Best_Practice.qmd
```
Füge dann Dein Kapitel wieder in _quarto.qmd ein, commite und erstelle einen neuen pull-request. Dann sollten die ganzen temporären Dateien nicht mehr im Projekt sein.

2023-07-29 14:48 UTC, jhorzek requested changes
Der commit beinhaltet viele temporäre Dateien

2023-07-29 15:22 UTC, jhorzek commented on Best_Practice.qmd
> +dat <- eignungstest
Das würde ich noch ändern, da das der guten Benennung widerspricht

2023-08-02 08:36 UTC, behnkec commented
@jhorzek Oh, danke, die sind mir irgendwie durchgerutscht, ich hoffe, es passst jetzt.

2023-08-02 08:38 UTC, behnkec commented on Best_Practice.qmd
> +dat <- eignungstest
Ich hatte das eigentlich bewusst gewählt, wenn das Skript eignungstest_analyse heißt, hat es für mich irgendwie Sinn ergeben, dass der Datensatz dann eignungstest heißt. Könnte ihn aber auch eignungstest_ergebnisse oder so nennen?

2023-08-02 08:56 UTC, jhorzek commented on Best_Practice.qmd
> +dat <- eignungstest
Sorry, ich hätte etwas genauer sein sollen: ich meinte das `dat`.

2023-08-02 09:22 UTC, closed without merging